language: python
python:
  - "3.6"
branches:
    only:
        - develop
services:
  - postgresql

#To install dependences
install:
  - pip install -r requirements.txt

before_script:
  - createuser kamaradeo --createdb
  - createdb mytestdatabase -U kamaradeo
  

#To run tests  
script: 
  - cd djangorest/
  - coverage run manage.py test

after_success:
  - coveralls