# Generated by Django 2.0.7 on 2018-07-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0002_auto_20180717_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('shoppinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Shoppinglist')),
            ],
        ),
    ]
