# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          TEST_DB: postgresql://deokamara:1234@localhost/mytestdatabase
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          SECRET_KEY: "********"
          POSTGRES_USER: deokamara
          POSTGRES_DB: mytestdatabase
          POSTGRES_PASSWORD: 1234

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/shoppinglistapp
    general:
      branches:
        only:
        - develop # list of branches to build
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          filters:
              branches:
                only: develop
          command: |
            . venv/bin/activate
            cd shoppinglistapp/
            coverage run --source=lists  manage.py test
            coveralls
      - store_artifacts:
          path: test-reports
          destination: test-reports

      