# Generated by Django 2.0.5 on 2018-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default='firstname', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Surname',
            field=models.CharField(default='surname', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email', max_length=255, unique=True),
        ),
    ]
