# Generated by Django 2.0.5 on 2018-05-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180526_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Surname',
            new_name='surname',
        ),
    ]
