# Generated by Django 2.0.5 on 2018-05-26 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180526_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
