# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180526_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
