# Generated by Django 2.0.7 on 2018-07-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180717_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='owner',
        ),
    ]
